log:
  level: DEBUG

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls: {}

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik
    watch: true

experimental:
  plugins:
    coraza-http-wasm-traefik:
      moduleName: github.com/jcchavezs/coraza-http-wasm-traefik
      version: v0.2.2
